GPU: 0,1
b1: 0.5
b2: 0.999
batch_size: 2
datasets_path: ../dataset/oabf/resonant_neuro
fmap: 16
gap_t: 30
gap_x: 90
gap_y: 90
lr: 5.0e-05
n_epochs: 10
output_dir: ./results
overlap_factor: 0.4
patch_t: 150
patch_x: 150
patch_y: 150
pth_path: ./pth/resonant_neuro_202508022117
scale_factor: 1
select_img_num: 1500
train_datasets_size: 1000
