GPU: '0'
b1: 0.5
b2: 0.999
batch_size: 1
datasets_path: ../dataset/dati_per_erzelli/mini2p_astro/good_example/2024Feb06-007/motion_corrected
fmap: 16
gap_t: 233
gap_x: 90
gap_y: 90
lr: 5.0e-05
n_epochs: 5
output_dir: ./results
overlap_factor: 0.4
patch_t: 150
patch_x: 150
patch_y: 150
pth_path: ./pth/motion_corrected_202507301407
scale_factor: 1
select_img_num: 1000000
train_datasets_size: 100
